<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_custom_group_checkin  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["selectList"]=true;

		$this->events["update"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List
function selectList($dataSource, $command)
{

		if(isset($_GET['member_id'])){
     $sql = "SELECT * FROM group_member_checkin WHERE group_id=".$_GET['group_id']." AND member_id=".$_GET['member_id']." ORDER BY group_member_checkin_id DESC";
}else{
    $sql = "SELECT * FROM group_member_checkin WHERE group_id=".$_GET['group_id']." ORDER BY group_member_checkin_id DESC";
}
$preparedSQL = DB::PrepareSQL( $sql );
$result = DB::Query( $preparedSQL );
if( !$result ) {
	$dataSource->setError( DB::LastError() );
	return false;
}
return $result;

;		
} // function selectList

		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Update
function update($dataSource, $command)
{

		$data=array();
$key=array();
$key['group_member_checkin_id']=$_POST['group_member_checkin_id'];
if($_POST['task']=='review'){
    $data['review_member']=$_POST['review_member'];
    $data['rating_member']=$_POST['rating_member'];
    $result=DB::Update("group_member_checkin",$data,$key);
}else{
    date_default_timezone_set('Asia/Makassar'); 
    $data['checkout_date']=date("Y-m-d H:i:s");
    $result=DB::Update("group_member_checkin",$data,$key);
}
if( !$result ) {
	$dataSource->setError( DB::LastError() );
	return false;
}
return $result;

;		
} // function update

		
		



}
?>
